copilot.addSound("pressureZero")
copilot.addSound("thrustSet")
copilot.addSound("oneHundred")
copilot.addSound("V1", 700)
copilot.addSound("rotate")
copilot.addSound("positiveClimb")
copilot.addSound("spoilers", 900)
copilot.addSound("noSpoilers", 800)
copilot.addSound("reverseGreen", 900)
copilot.addSound("noReverseLeft", 1200)
copilot.addSound("noReverseRight", 1300)
copilot.addSound("noReverse", 1000)
copilot.addSound("decel", 600)
copilot.addSound("noDecel", 900)
copilot.addSound("seventy")

copilot.addSound("fullLeft_1")
copilot.addSound("fullLeft_2")
copilot.addSound("fullRight_1")
copilot.addSound("fullRight_2")
copilot.addSound("fullUp")
copilot.addSound("fullDown")
copilot.addSound("neutral_1")
copilot.addSound("neutral_2")
copilot.addSound("neutral_3")

copilot.addSound("flapsOne", 1500)
copilot.addSound("flapsTwo", 1600)
copilot.addSound("flapsThree", 1800)
copilot.addSound("flapsTree", 1600)
copilot.addSound("flapsFull", 1600)
copilot.addSound("flapsZero", 1400)
