title = 'Copilot for FSLabs 1.1.6'

project = 'Copilot for FSLabs 1.1.6'

file = {
  'Modules/FSLabs Copilot/copilot/Event.lua',
  'Modules/FSLabs Copilot.lua',
  'Modules/FSLabs Copilot/copilot/helpers.lua',
  'Modules/FSL2lua/FSL2Lua/FSL2Lua.lua',
  'FSL2Lua/Joystick.h'
}

format = 'markdown'

readme = {
  'topics',
}

examples={'examples'}

backtick_references = true

kind_names={topic='Manual',module='Libraries'}

use_markdown_titles = true

no_space_before_args = true

convert_opt = false

pretty='lxsh'