title = 'Copilot for FSLabs 1.1.1'

project = 'Copilot for FSLabs 1.1.1'

file = {
  'Modules/FSLabs Copilot/copilot/Event.lua',
  'Modules/FSLabs Copilot.lua',
  'Modules/FSLabs Copilot/copilot/helpers.lua',
  'Modules/FSL2lua/FSL2Lua/FSL2Lua.lua'
   
}

format = 'discount'

readme = {
  'topics',
}

examples={'examples'}

kind_names={topic='Manual',module='Libraries'}

use_markdown_titles = true

no_space_before_args = true

convert_opt = false

pretty='lxsh'