copilot.addCallout("pressureZero", "ogg")
copilot.addCallout("thrustSet", "ogg")
copilot.addCallout("oneHundred", "ogg")
copilot.addCallout("V1", "ogg", 700)
copilot.addCallout("rotate", "ogg")
copilot.addCallout("positiveClimb", "ogg")
copilot.addCallout("spoilers", "ogg", 900)
copilot.addCallout("noSpoilers", "ogg", 800)
copilot.addCallout("reverseGreen", "ogg", 1300)
copilot.addCallout("noReverseLeft", "ogg", 1200)
copilot.addCallout("noReverseRight", "ogg", 1300)
copilot.addCallout("noReverse", "ogg", 1000)
copilot.addCallout("decel", "ogg", 600)
copilot.addCallout("noDecel", "ogg", 900)
copilot.addCallout("seventy", "ogg")

copilot.addCallout("fullLeft_1", "ogg")
copilot.addCallout("fullLeft_2", "ogg")
copilot.addCallout("fullRight_1", "ogg")
copilot.addCallout("fullRight_2", "ogg")
copilot.addCallout("fullUp", "ogg")
copilot.addCallout("fullDown", "ogg")
copilot.addCallout("neutral_1", "ogg")
copilot.addCallout("neutral_2", "ogg")
copilot.addCallout("neutral_3", "ogg")

copilot.addCallout("flapsOne", "ogg", 1500)
copilot.addCallout("flapsTwo", "ogg", 1600)
copilot.addCallout("flapsThree", "ogg", 1800)
copilot.addCallout("flapsTree", "ogg", 1600)
copilot.addCallout("flapsFull", "ogg", 1600)
copilot.addCallout("flapsZero", "ogg", 1400)
