copilot.addCallout("pressureZero")
copilot.addCallout("thrustSet")
copilot.addCallout("oneHundred")
copilot.addCallout("V1", 700)
copilot.addCallout("rotate")
copilot.addCallout("positiveClimb")
copilot.addCallout("spoilers", 900)
copilot.addCallout("noSpoilers", 800)
copilot.addCallout("reverseGreen", 900)
copilot.addCallout("noReverseLeft", 1200)
copilot.addCallout("noReverseRight", 1300)
copilot.addCallout("noReverse", 1000)
copilot.addCallout("decel", 600)
copilot.addCallout("noDecel", 900)
copilot.addCallout("seventy")

copilot.addCallout("fullLeft_1")
copilot.addCallout("fullLeft_2")
copilot.addCallout("fullRight_1")
copilot.addCallout("fullRight_2")
copilot.addCallout("fullUp")
copilot.addCallout("fullDown")
copilot.addCallout("neutral_1")
copilot.addCallout("neutral_2")
copilot.addCallout("neutral_3")

copilot.addCallout("flapsOne", 1500)
copilot.addCallout("flapsTwo", 1600)
copilot.addCallout("flapsThree", 1800)
copilot.addCallout("flapsTree", 1600)
copilot.addCallout("flapsFull", 1600)
copilot.addCallout("flapsZero", 1400)
